org: raisaalmeida
app: aws-scrapper-bgc
service: aws-scrapper-bgc
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x

functions:
  scrapper:
    handler: ./src/scrapper.handler
